version: '3'

services:
  loan-app:
    build: .
    image: gurkancnk/loanproject:latest
    container_name: loan-prediction-app
    ports:
      - "8501:8501"
    volumes:
      - ./data:/app/data
      - ./models:/app/models
    environment:
      - STREAMLIT_SERVER_PORT=8501
      - STREAMLIT_SERVER_HEADLESS=true
    restart: unless-stopped 